<?xml version="1.0" encoding="UTF-8"?>
<org.eclipse.epf.uma:TaskDescription xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:org.eclipse.epf.uma="http://www.eclipse.org/epf/uma/1.0.5/uma.ecore"
    xmlns:epf="http://www.eclipse.org/epf" epf:version="1.5.0" xmi:id="-t9u_xCSvgd5KqXkqKJUv9A"
    name=",_6DwnEGvBEd6yrb4fWyiJGw" guid="-t9u_xCSvgd5KqXkqKJUv9A" changeDate="2009-11-11T12:51:30.912-0300">
  <mainDescription>main description</mainDescription>
  <keyConsiderations>key</keyConsiderations>
  <purpose>&lt;p>&#xD;
    purpose&#xD;
&lt;/p></purpose>
  <alternatives>alternatives</alternatives>
</org.eclipse.epf.uma:TaskDescription>
